services:
  dovetail:
    build: .
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dovetail-state:/var/lib/dovetail
    restart: unless-stopped

  # test server
  hello:
    image: traefik/whoami
    labels:
      dovetail.name: "hello"
      dovetail.port: "80"

volumes:
  dovetail-state:
